- name: "Install system print client"
  ansible.builtin.include_tasks: print_client/main.yml

- name: "Remove printer only, then take no further action"
  ansible.builtin.include_tasks: remove_printer/main.yml
  when: remove_printer_only

# - name: "Configure a printer for use"
#   ansible.builtin.include_tasks: configure/main.yml

