- name: "Install the 'cups' print server/client package"
  ansible.builtin.package:
    name: cups
    state: present
  become: true
  become_user: root

- name: "Install the 'cups-pdf' print-to-pdf-support package"
  ansible.builtin.package:
    name: cups-pdf
    state: present
  become: true
  become_user: root
  when: enable_print_to_pdf

# - name: "Ensure 'cups' service is started, and enable it to start at boot"
#   ansible.builtin.service:
#     name: cups
#     state: started
#     enabled: yes
#   become: true
#   become_user: root

