# Follow all steps, for both print-server and print-client:
#  https://docs.freebsd.org/en/articles/cups/

- name: "Install the 'cups' print server/client package"
  ansible.builtin.package:
    name: cups
    state: present
  become: true
  become_user: root

- name: "Install the 'cups-pdf' print-to-pdf-support package"
  ansible.builtin.package:
    name: cups-pdf
    state: present
  become: true
  become_user: root
  when: enable_print_to_pdf

- name: "Ensure 'cupsd' service is started, and enable it to start at boot"
  ansible.builtin.service:
    name: cupsd
    state: started
    enabled: yes
  become: true
  become_user: root

